### ISSUE TITLE
--link-dest incremental syncing

### ISSUE THREAD

**Issue by okdewit** [mattes/autorsync#2]
Hey @mattes!

Very interesting script. I'm not that well-versed with node yet, and was wondering whether functionality for separate & incremental rsync destinations would be hard to implement.

I'm currently aiming for a script which watches a directory, and makes a _new_ backup every time a file changes in the watched source directory. The destination would consist of incrementally numbered or timestamped directories, and it would pass the previous backup directory as a --link-dest option every time the event is triggered.

I'm going to give it a shot myself, but would love any input you have on this!

**Comment by mattes** [comment]
Hey @feroxium 

Haven't worked on that code in a while, but I guess it should be possible. If you have any further questions, just let me know. Happy hacking ;-)
